// SPDX-License-Identifier: __SOLC_SPDX__
pragma solidity >=__SOLC_VERSION__;

/// ------------------------------------------------------------------------------------------------------------
///
/// NOTE: This file is auto-generated by Gemforge.
///
/// ------------------------------------------------------------------------------------------------------------

import { IDiamondCut } from "__LIB_DIAMOND_PATH__/contracts/interfaces/IDiamondCut.sol";
import { IDiamondProxy } from "./IDiamondProxy.sol";

__FACET_IMPORTS__

library LibDiamondHelper {
  function deployFacetsAndGetCuts() internal returns (IDiamondCut.FacetCut[] memory cut) {
    // initialize the diamond as well as cut in all facets
    cut = new IDiamondCut.FacetCut[](__NUM_FACETS__);

__CUTS__
  }
}
