// SPDX-License-Identifier: __SOLC_SPDX__
pragma solidity >=__SOLC_VERSION__;

/// ------------------------------------------------------------------------------------------------------------
///
/// NOTE: This file is auto-generated by GemForge, please DO NOT modify it directly.
///
/// ------------------------------------------------------------------------------------------------------------

__INTERFACE_IMPORTS__

enum FacetAddressIndex {
  __FACET_NAMES__
}

library LibFacets {
  function getFacetNames() internal pure returns (string[] memory facetNames) {
    __GET_FACET_NAMES__
  }

  function createDiamondFunctionsCut(address[] memory facetAddresses) internal pure returns (IDiamondCut.FacetCut[] memory cut) {
    __DIAMOND_FUNCTIONS_CUT__
  }

  function deployFacets() internal returns (address[] memory facetAddresses) {
    __DEPLOY_FACETS__
  }

  function deployAndCutFacets(address proxy) internal {
    address[] memory facetAddresses = deployFacets();
    IDiamondCut.FacetCut[] memory cut = createDiamondFunctionsCut(facetAddresses);
    IDiamondCut(proxy).diamondCut(cut, address(0), "");
  }
}
